In [ ]:
pip install numpy


In [3]:
import numpy as np

In [6]:
l=[1,2.3,"hello"]
l

[1, 2.3, 'hello']

In [7]:
arr=np.array(l)

In [8]:
arr

array(['1', '2.3', 'hello'], dtype='<U32')

In [9]:
n=[1, 2.3]
np.array(n)

array([1. , 2.3])

In [10]:
list=[[1,2,3],[4,5,6],[7,8,9]]
list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.random.randn(5)

array([ 0.03763223, -0.38091405,  0.54261292, -0.00316925,  2.06582262])

In [64]:
np.random.randint(1,21,20)

array([11, 12, 10,  5,  9,  7, 19,  3,  2,  8, 16,  5,  7,  9, 16,  8,  4,
       19,  3,  6], dtype=int32)

In [62]:
np.random.rand(4,2)

array([[0.25928545, 0.0168973 ],
       [0.56727324, 0.64432437],
       [0.09683233, 0.68099103],
       [0.59949309, 0.5858295 ]])

In [65]:
ad=np.arange(1,21)

In [66]:
ad

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
ad=ad.reshape(5,4)

In [71]:
ad.max()

np.int64(20)

In [72]:
ad.argmax()

np.int64(19)

In [73]:
adeel=np.arange(1,11)

In [74]:
adeel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
adeel.size

10

In [21]:
l=[[1,2,3],[4,5,6]]
ar=np.array(l)

In [22]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
ar.shape

(2, 3)

In [24]:
ar.size

6

In [25]:
ar.sum()

np.int64(21)

In [26]:
np.sum(ar,axis=0)

array([5, 7, 9])

In [27]:
np.sum(ar,axis=1)

array([ 6, 15])

In [13]:
x=np.random.randint(1,101,100)

In [14]:
z=x.reshape(10,10)

In [15]:
z

array([[39, 35, 94, 46, 17, 74, 21, 70,  8, 21],
       [50, 53, 31, 79,  1, 31, 37, 12, 11, 96],
       [61, 61, 13, 75, 72, 77, 23, 30, 23, 35],
       [55, 71, 73,  3,  3, 97, 51, 58, 12, 52],
       [59, 88, 35, 28, 78, 41, 76, 22, 11, 52],
       [45,  2, 83, 89, 25, 63, 32, 89,  8, 79],
       [12, 36, 97, 70, 33, 17, 11, 61, 93, 78],
       [22, 13,  6, 45, 89, 68, 64, 34, 36, 71],
       [33, 63, 76, 57, 10, 57,  7, 62, 90, 56],
       [84, 59, 21, 72, 70, 82, 78, 63, 69, 49]], dtype=int32)

In [17]:
z[0:,0] +10

array([49, 60, 71, 65, 69, 55, 22, 32, 43, 94], dtype=int32)

In [16]:
z+10

array([[ 49,  45, 104,  56,  27,  84,  31,  80,  18,  31],
       [ 60,  63,  41,  89,  11,  41,  47,  22,  21, 106],
       [ 71,  71,  23,  85,  82,  87,  33,  40,  33,  45],
       [ 65,  81,  83,  13,  13, 107,  61,  68,  22,  62],
       [ 69,  98,  45,  38,  88,  51,  86,  32,  21,  62],
       [ 55,  12,  93,  99,  35,  73,  42,  99,  18,  89],
       [ 22,  46, 107,  80,  43,  27,  21,  71, 103,  88],
       [ 32,  23,  16,  55,  99,  78,  74,  44,  46,  81],
       [ 43,  73,  86,  67,  20,  67,  17,  72, 100,  66],
       [ 94,  69,  31,  82,  80,  92,  88,  73,  79,  59]], dtype=int32)

In [12]:
pract=np.arange(11,21)
pract

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
pract[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [1]:
a1=[1,2,3,4,5]
a2=[6,7,8,9,10]

a1+a2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
arr1=np.array(a1)
arr2=np.array(a2)

In [7]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [8]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [10]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
arr1//arr2

array([0, 0, 0, 0, 0])

In [44]:
a =[1,2,3,4,5,7]


In [45]:
a

[1, 2, 3, 4, 5, 7]

In [47]:
b=a
b[4]=34

In [48]:
b

[1, 2, 3, 4, 34, 7]

In [49]:
a

[1, 2, 3, 4, 34, 7]

In [51]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[6,2],[3,6]])

In [52]:
A


array([[1, 2],
       [3, 4]])

In [53]:
B

array([[6, 2],
       [3, 6]])

In [54]:
A@B

array([[12, 14],
       [30, 30]])

In [56]:
c=np.dot(A,B)

In [57]:
c

array([[12, 14],
       [30, 30]])

In [58]:
c.T

array([[12, 30],
       [14, 30]])

In [69]:
a=np.arange(1,11)
b=np.arange(11,21)

In [62]:
hsta=np.hstack((a,b))

In [63]:
hsta

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
vsta=np.vstack((a,b))
vsta

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [80]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [78]:
c=np.hsplit(arr,3)
c

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30]])]

In [83]:
d=np.vsplit(arr,6)
d

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]])]