Valid Sudoko 

In [ ]:
import numpy as np


In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [20]:
for i in s[0:,0:]:
    print(i.sum())

45
45
45
45
45
45
45
45
45


In [27]:
n=np.sum(s,axis=0)
for i in n:
    if i!=45:
        print("invalid sudoku")
        break
else:
    print("valid soduko")
        

valid soduko


In [29]:
b=np.sum(s,axis=1)
b==45


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [42]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])





In [46]:
for i in range(0,9,3):
    for j in range(0,9,3):


        n=(s[i:i+3,j:j+3])
        print(n.sum())


    

45
45
45
45
45
45
45
45
45


In [70]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 86, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

Get the shape of the matrix.

In [49]:
data.shape

(5, 3)

#Find the average age of students.

In [52]:
c=data[0:,0].mean()
c

np.float64(18.4)

#Extract Math marks of all students.

In [53]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [54]:
data[0:,1]

array([85, 92, 76, 65, 90])

#Find the highest Science mark.

In [55]:
data[0:,2].max()

np.int64(95)

#Get details of the student who scored more than 90 in Math.

In [57]:
data[data[0:,1] >90]

array([[19, 92, 88]])

#Increase Math marks of all students by 5.

In [58]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [59]:
data[0:,1]+5

array([90, 97, 81, 70, 95])

#Find how many students are younger than 19.

In [65]:
len(data[data[0:,0]<19])

3

#Calculate the average marks in each subject (column-wise mean)

In [66]:
np.mean(data[0:,1:],axis=0)

array([81.6, 83.2])

#Get data of students who scored at least 80 in both subjects.

In [71]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [17, 86, 95],
       [20, 90, 85]])

#Replace all Science marks < 79 with 0.

In [76]:
data[:,2][data[:,2] <79]=0
data


array([[18, 85,  0],
       [19, 92, 88],
       [17, 86, 95],
       [18, 65,  0],
       [20, 90, 85]])