In [1]:
import numpy as np

In [2]:
sales = np.array([
    [1200,1500,1700,1300],
    [1400,1600,1800,1500],
    [1700,1800,2100,1900],
    [1300,1200,1400,1500],
    [1800,2000,2200,2100]
])

In [3]:
# Total_Rev=np.sum(sales[:,:])
# Total_Rev
Total_Rev=sales[:].sum(axis=1)
for i ,c in enumerate(Total_Rev,start=1):
    print(f"{i} : {Total_Rev[i-1]}")


1 : 5700
2 : 6300
3 : 7500
4 : 5400
5 : 8100


In [4]:
# Find the total weekly revenue generated by each product.
Total_Rev=sales[:].sum(axis=0)
# for i ,c in enumerate(Total_Rev,start=1):
#     print(f"{i} : {Total_Rev[i-1]}")
Total_Rev

array([7400, 8100, 9200, 8300])

In [5]:
# Task 3 — Average Sales
# Description

# Find

# Average sales per day
# Average sales per product

In [6]:
sales.mean(axis=1)

array([1425., 1575., 1875., 1350., 2025.])

In [7]:
sales.mean(axis=0)

array([1480., 1620., 1840., 1660.])

In [8]:
Total_Rev.max()

np.int64(9200)

ADDING ANOTHER PRODUCT OR COLUMN IN DATA SET :

In [12]:
z=np.array([1000,1100,1200,900,1300])
np.column_stack((sales,z))

array([[1200, 1500, 1700, 1300, 1000, 1000],
       [1400, 1600, 1800, 1500, 1100, 1100],
       [1700, 1800, 2100, 1900, 1200, 1200],
       [1300, 1200, 1400, 1500,  900,  900],
       [1800, 2000, 2200, 2100, 1300, 1300]])

In [10]:
days=["monday","tuesday","thursday","friday","saturday"]
n=sales[0,:].sum()
hj=[days[0]]
print(f"{n} :{hj}")

6700 :['monday']


In [14]:
sales

array([[1200, 1500, 1700, 1300, 1000],
       [1400, 1600, 1800, 1500, 1100],
       [1700, 1800, 2100, 1900, 1200],
       [1300, 1200, 1400, 1500,  900],
       [1800, 2000, 2200, 2100, 1300]])

In [15]:
# highest individuals
products = ["Bread", "Milk", "Rice", "Eggs"]
row, col = np.unravel_index(sales.argmax(), sales.shape)

print("Day:", days[row])
print("Product:", products[col])
print("Sale:", sales[row, col])

Day: saturday
Product: Rice
Sale: 2200
